# Hyprland wallpaper utility
{
  services.hyprpaper = {
    enable = true;
    settings = {
      splash = false;
      # Loaded from runtime theme — generated by applyTheme activation before login
      wallpaper = {
        monitor = "";
        path = "/home/askeko/.config/theme/current/wallpaper";
      };
    };
  };
}
